server.port=8080
spring.application.name=websocket-demo

# Logging
logging.level.org.springframework=INFO
logging.level.com.example.websocket=DEBUG


spring.datasource.url= jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1
driverClassName=org.h2.Driver
username=sa
jpa.hibernate.ddl.auto= update

app.jwt.secret= "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_CHANGE_ME"
issuer= "bank-backend"
accessTokenMinutes= 30

challenge.ttlSeconds= 90