server.port=8080
spring.application.name=websocket-demo


spring.datasource.url= jdbc:h2:mem:bank;DB_CLOSE_DELAY=-1
driverClassName=org.h2.Driver
username= sa
password=
jpa.hibernate.ddl-auto=update
properties.hibernate.format_sql= true

app.jwt.secret= "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_CHANGE_ME"
issuer= "bank-backend"
accessTokenMinutes= 30

challenge.ttlSeconds= 90

app.jwt.issuer = "bank-backend"
app.challenge.ttlSeconds=90
app.jwt.accessTokenMinutes=30

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
